
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    image: perteghella/devfest-modena-2024:1.0
    hostname: web1
    ports:
      - '8001:5000'
  web2:
    restart: on-failure
    image: perteghella/devfest-modena-2024:1.0
    hostname: web2
    ports:
      - '8002:5000'
  nginx:
    build: ./nginx
    ports:
    - '8000:80'
    depends_on:
    - web1
    - web2