
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  web:
    restart: on-failure
    image: perteghella/devfest-modena-2024:1.0
    hostname: web1
    ports:
      - '8000:5000'
